version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Building the application"
      - mvn clean package
artifacts:
  files:
    - target/*.jar
    - .platform/**/*
    - .ebextensions/**/*