version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing dependencies...
      - npm install # Install Node.js dependencies for obfuscation
  pre_build:
    commands:
      - echo Running pre-build steps...
      - npm run obfuscate # Run JavaScript obfuscation
  build:
    commands:
      - echo Building the application...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/mrtasks-0.0.1-SNAPSHOT.jar
    - Procfile
    - .ebextensions/**/*
    - .platform/**/*
cache:
  paths:
    - '/root/.m2/**/*' # Cache Maven dependencies
    - '/root/.npm/**/*' # Cache npm dependencies