version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean package
artifacts:
  files:
    - target/mrtasks-0.0.1-SNAPSHOT.jar
    - Procfile